# ***************************************************************************
# *   Copyright (c) 2025 David Carter <dcarter@davidcarter.ca>              *
# *                                                                         *
# *   This program is free software; you can redistribute it and/or modify  *
# *   it under the terms of the GNU Lesser General Public License (LGPL)    *
# *   as published by the Free Software Foundation; either version 2 of     *
# *   the License, or (at your option) any later version.                   *
# *   for detail see the LICENCE text file.                                 *
# *                                                                         *
# *   This program is distributed in the hope that it will be useful,       *
# *   but WITHOUT ANY WARRANTY; without even the implied warranty of        *
# *   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the         *
# *   GNU Library General Public License for more details.                  *
# *                                                                         *
# *   You should have received a copy of the GNU Library General Public     *
# *   License along with this program; if not, write to the Free Software   *
# *   Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  *
# *   USA                                                                   *
# *                                                                         *
# ***************************************************************************
"""Class for CFD Reports"""

__author__ = "David Carter"
__url__ = "https://www.davesrocketshop.com"

import FreeCAD
import os

from docx import Document
from docx.shared import Inches

from CfdOF import CfdTools

class CFDReport:

    def __init__(self, analysis):
        # Import here to prevent circular imports
        from Rocket.cfd.CFDUtil import caliber, finThickness
        from Rocket.cfd.FeatureCFDRocket import calcFrontalArea

        self._analysis = analysis
        self._path = os.path.join(CfdTools.getOutputPath(self._analysis), 'CFD Report.docx')

        self._CP = False

        self._frontalArea = calcFrontalArea(self._analysis.Shape)
        self._diameter = caliber(self._analysis.Rocket)
        self._thickness = finThickness(self._analysis.Rocket)
        box = self._analysis.Shape.BoundBox
        self._length = box.XLength

    def getPath(self):
        return self._path

    def generate(self):
        self._document = Document()
        self.generateIntro()
        if self._CP:
            self.generateCP()
        self.generateCD()
        self.generateCL()
        self._document.save(self._path)

    def generateIntro(self):
        self._document.add_heading('CFD Report', 0)

        p = self._document.add_paragraph("This is an automated report generated by the Rocket Workbench. "\
                                         "It was created by running a CFD analysis on the document '{}'."\
                                            .format(FreeCAD.ActiveDocument.Label))
        # p.add_run('bold').bold = True
        # p.add_run(' and some ')
        # p.add_run('italic.').italic = True

        self._document.add_paragraph("Details about the study, including the rocket")

        table = self._document.add_table(rows=4, cols=2, style='Table Grid')
        hdr_cells = table.columns[0].cells
        hdr_cells[0].text = 'Length'
        hdr_cells[1].text = 'Diameter'
        hdr_cells[2].text = 'Minimum Fin Thickness'
        hdr_cells[3].text = 'Frontal Area'
        data_cells = table.columns[1].cells
        data_cells[0].text = FreeCAD.Units.Quantity("{} mm".format(self._length)).UserString
        data_cells[1].text = FreeCAD.Units.Quantity("{} mm".format(self._diameter)).UserString
        data_cells[2].text = FreeCAD.Units.Quantity("{} mm".format(self._thickness)).UserString
        data_cells[3].text = FreeCAD.Units.Quantity("{} mm^2".format(self._frontalArea)).UserString

        self._document.add_heading('Study Parameters', level=1)

        self._document.add_paragraph("This study varied the following parameters:")
        table = self._document.add_table(rows=1, cols=1, style='Table Grid')
        hdr_cells = table.rows[0].cells
        hdr_cells[0].text = 'Angle of Attack'
        for angle in self._analysis.AOAList:
            row_cells = table.add_row().cells
            row_cells[0].text = str(angle)

        non_zero = 0
        for angle in self._analysis.AOAList:
            if angle != 0:
                non_zero += 1
        if non_zero < 2:
            self._CP = False
            p = self._document.add_paragraph()
            p.add_run("NOTE: It is not possible to calculate the center of pressure at an "\
                                        "angle of attack of 0. It must be calculated at multiple points close "\
                                        "to 0 and inferred using l'Hopitals rule.").bold = True
            p = self._document.add_paragraph()
            p.add_run('This study is unable to determine Center of Pressure.').italic = True
        else:
            self._CP = True

        self._document.add_page_break()

    def generateCP(self):
        self._document.add_heading('Center of Pressure', level=1)
        p = self._document.add_paragraph("")
        p.add_run("NOTE: It is not possible to calculate the center of pressure at an "\
                                    "angle of attack of 0. It must be calculated at multiple points close "\
                                    "to 0 and inferred using l'Hopitals rule.").bold = True
        self._document.add_paragraph("Center of Pressure at multiple angles of attack")
        self._document.add_page_break()

    def generateCD(self):
        self._document.add_heading('Drag', level=1)
        self._document.add_paragraph("Drag coefficient at multiple angles of attack")
        self._document.add_page_break()

    def generateCL(self):
        self._document.add_heading('Lift', level=1)
        self._document.add_paragraph("Lift coefficient at multiple angles of attach")
